In [1]:
import ScraperFC as sfc  # LEAVE THIS!

In [2]:
fb = sfc.FBref()
match = fb.scrape_match('https://fbref.com/en/matches/67ed3ba2/Brentford-Tottenham-Hotspur-August-13-2023-Premier-League')
match

,Link,Date,Stage,Home Team,Away Team,Home Team ID,Away Team ID,Home Goals,Away Goals,Home Player Stats,Away Player Stats,Shots
0,https://fbref.com/en/matches/67ed3ba2/Brentfor...,"Sunday August 13, 2023",Premier League (Matchweek 1),Brentford,Tottenham Hotspur,cd051869,361ca564,2,2,Summary Unnamed: 0_level_0 Unname...,Summary Unnamed: 0_level_0 Unnamed...,Both Unnamed: 0_level_0 Unnamed: 1_leve...

In [3]:
match.loc[0,'Away Player Stats']['Summary'].head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
              Player                  #             Nation                Pos
0        Richarlison                9.0             br BRA                 FW
1      Son Heung-min                7.0             kr KOR                 LW
2       Ivan Perišić               14.0             hr CRO                 LW
3   Dejan Kulusevski               21.0             se SWE                 RW
4     James Maddison               10.0            eng ENG                 AM

  Unnamed: 4_level_0 Unnamed: 5_level_0 Performance               ... SCA      \
                 Age                Min         Gls Ast PK PKatt  ... SCA GCA
0             26-095                 90           0   0  0     0  ...   1   0
1             31-036                 74           0   0  0     0  ...   2   0
2             34-192                 16           0   0  0     0  ...   2   0
3             23-110                 90           0   0  0     0  ...   5   0
4             26-263                 90           0   2  0     0  ...   8   3

  Passes                Carries      Take-Ons
     Cmp Att  Cmp% PrgP Carries PrgC      Att Succ
0     13  18  72.2    1      21    1        5    3
1     31  37  83.8    5      33    3        2    1
2     11  16  68.8    3      13    2        3    3
3     49  60  81.7    3      51    4        1    1
4     58  75  77.3    7      68    1        2    0

[5 rows x 31 columns]

In [4]:
season = fb.scrape_stats('2020-2021', league='EPL', stat_category='standard')
season

(   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                 Squad               # Pl                Age
 0             Arsenal                 29               25.9
 1         Aston Villa                 24               25.2
 2            Brighton                 27               25.8
 3             Burnley                 25               28.3
 4             Chelsea                 27               26.0
 5      Crystal Palace                 24               29.1
 6             Everton                 29               26.3
 7              Fulham                 28               25.2
 8        Leeds United                 23               26.1
 9      Leicester City                 27               26.5
 10          Liverpool                 28               26.8
 11    Manchester City                 24               26.1
 12     Manchester Utd                 29               25.6
 13      Newcastle Utd                 27               27.1
 14      Sheffield Utd                 27               26.7
 15        Southampton                 29               26.6
 16          Tottenham                 24               27.2
 17          West Brom                 30               26.4
 18           West Ham                 24               27.8
 19             Wolves                 27               26.3

    Unnamed: 3_level_0 Playing Time                    Performance      ...  \
                  Poss           MP Starts   Min   90s         Gls Ast  ...
 0                53.5           38    418  3420  38.0          53  38  ...
 1                48.5           38    418  3420  38.0          52  38  ...
 2                51.1           38    418  3420  38.0          39  24  ...
 3                42.1           38    418  3420  38.0          32  20  ...
 4                60.9           38    418  3420  38.0          56  38  ...
 5                40.6           38    418  3420  38.0          39  29  ...
 6                46.4           38    418  3420  38.0          45  32  ...
 7                49.7           38    418  3420  38.0          26  18  ...
 8                57.3           38    418  3420  38.0          60  45  ...
 9                54.3           38    418  3420  38.0          64  45  ...
 10               62.1           38    418  3420  38.0          65  43  ...
 11               63.5           38    418  3420  38.0          82  55  ...
 12               55.7           38    418  3420  38.0          70  51  ...
 13               38.8           38    418  3420  38.0          44  26  ...
 14               41.7           38    418  3420  38.0          19  13  ...
 15               52.0           38    418  3420  38.0          47  33  ...
 16               51.6           38    418  3420  38.0          66  50  ...
 17               37.9           38    418  3420  38.0          33  20  ...
 18               43.2           38    418  3420  38.0          60  46  ...
 19               49.3           38    418  3420  38.0          34  21  ...

    Per 90 Minutes                                                       \
               Ast   G+A  G-PK G+A-PK    xG   xAG xG+xAG  npxG npxG+xAG
 0            1.00  2.39  1.24   2.24  1.36  0.92   2.29  1.24     2.16
 1            1.00  2.37  1.24   2.24  1.38  0.98   2.37  1.26     2.25
 2            0.63  1.66  0.87   1.50  1.34  0.87   2.21  1.15     2.03
 3            0.53  1.37  0.76   1.29  1.03  0.73   1.76  0.97     1.70
 4            1.00  2.47  1.26   2.26  1.64  1.09   2.73  1.43     2.53
 5            0.76  1.79  0.95   1.71  0.90  0.62   1.52  0.82     1.44
 6            0.84  2.03  1.08   1.92  1.20  0.81   2.01  1.10     1.91
 7            0.47  1.16  0.61   1.08  1.07  0.69   1.76  0.95     1.64
 8            1.18  2.76  1.47   2.66  1.46  1.10   2.57  1.38     2.48
 9            1.18  2.87  1.42   2.61  1.47  0.89   2.36  1.22     2.11
 10           1.13  2.84  1.55   2.68  1.78  1.27   3.05  1.65     2.92
 11           1.45  3.61  2.03   3.47  1.80  1.19   2.99  1.61     2.81
 12           1.34  3.18  1.58   2.92  1.58  1.10   2.68  1.35     2.45
 13           0.68  1.84  1.00   1.68  1.14  0.76   1.91  1.00     1.76
 14           0.34  0.84  0.42   0.76  0.86  0.66   1.52  0.78     1.43
 15           0.87  2.11  1.11   1.97  1.09  0.68   1.77  0.96     1.64
 16           1.32  3.05  1.61   2.92  1.40  0.93   2.33  1.29     2.22
 17           0.53  1.39  0.76   1.29  0.94  0.64   1.59  0.86     1.50
 18           1.21  2.79  1.53   2.74  1.46  1.04   2.50  1.37     2.41
 19           0.55  1.45  0.79   1.34  0.96  0.63   1.60  0.88     1.51

      Team ID

 0   18bb7c10
 1   8602292d
 2   d07537b9
 3   943e8050
 4   cff3d9bb
 5   47c64c55
 6   d3fd31cc
 7   fd962109
 8   5bfb9659
 9   a2d435b3
 10  822bd0ba
 11  b8fd03ef
 12  19538871
 13  b2b47a98
 14  1df6b87e
 15  33c895d4
 16  361ca564
 17  60c6b05f
 18  7c21e445
 19  8cec06e1

 [20 rows x 33 columns],
     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                  Squad               # Pl                Age
 0           vs Arsenal                 29               26.7
 1       vs Aston Villa                 24               26.7
 2          vs Brighton                 27               26.4
 3           vs Burnley                 25               26.6
 4           vs Chelsea                 27               26.3
 5    vs Crystal Palace                 24               26.4
 6           vs Everton                 29               26.4
 7            vs Fulham                 28               26.6
 8      vs Leeds United                 23               26.5
 9    vs Leicester City                 27               26.5
 10        vs Liverpool                 28               26.6
 11  vs Manchester City                 24               26.4
 12   vs Manchester Utd                 29               26.6
 13    vs Newcastle Utd                 27               26.6
 14    vs Sheffield Utd                 27               26.7
 15      vs Southampton                 29               26.5
 16        vs Tottenham                 24               26.5
 17        vs West Brom                 30               26.6
 18         vs West Ham                 24               26.6
 19           vs Wolves                 27               26.6

    Unnamed: 3_level_0 Playing Time                    Performance      ...  \
                  Poss           MP Starts   Min   90s         Gls Ast  ...
 0                46.2           38    418  3420  38.0          35  25  ...
 1                51.9           38    418  3420  38.0          45  30  ...
 2                48.7           38    418  3420  38.0          44  30  ...
 3                58.3           38    418  3420  38.0          54  47  ...
 4                38.6           38    418  3420  38.0          35  26  ...
 5                59.9           38    418  3420  38.0          66  47  ...
 6                53.5           38    418  3420  38.0          47  33  ...
 7                50.1           38    418  3420  38.0          52  34  ...
 8                42.4           38    418  3420  38.0          52  36  ...
 9                45.4           38    418  3420  38.0          48  29  ...
 10               37.6           38    418  3420  38.0          42  29  ...
 11               36.1           38    418  3420  38.0          31  17  ...
 12               44.2           38    418  3420  38.0          42  28  ...
 13               61.8           38    418  3420  38.0          59  41  ...
 14               58.5           38    418  3420  38.0          60  45  ...
 15               47.8           38    418  3420  38.0          67  44  ...
 16               48.3           38    418  3420  38.0          42  24  ...
 17               62.4           38    418  3420  38.0          73  52  ...
 18               57.1           38    418  3420  38.0          43  34  ...
 19               50.7           38    418  3420  38.0          49  34  ...

    Per 90 Minutes                                                       \
               Ast   G+A  G-PK G+A-PK    xG   xAG xG+xAG  npxG npxG+xAG
 0            0.66  1.58  0.87   1.53  1.13  0.84   1.97  1.07     1.91
 1            0.79  1.97  1.05   1.84  1.34  0.82   2.16  1.22     2.04
 2            0.79  1.95  1.00   1.79  0.93  0.61   1.54  0.79     1.40
 3            1.24  2.66  1.34   2.58  1.44  1.12   2.56  1.38     2.50
 4            0.68  1.61  0.84   1.53  0.80  0.53   1.33  0.71     1.25
 5            1.24  2.97  1.66   2.89  1.53  1.12   2.66  1.45     2.57
 6            0.87  2.11  1.16   2.03  1.32  0.89   2.21  1.24     2.12
 7            0.89  2.26  1.18   2.08  1.38  0.98   2.37  1.24     2.22
 8            0.95  2.32  1.16   2.11  1.52  1.03   2.56  1.33     2.37
 9            0.76  2.03  1.16   1.92  1.21  0.87   2.08  1.13     2.00
 10           0.76  1.87  1.00   1.76  1.13  0.71   1.84  0.97     1.68
 11           0.45  1.26  0.61   1.05  0.80  0.40   1.19  0.59     0.98
 12           0.74  1.84  1.00   1.74  1.09  0.75   1.84  1.01     1.76
 13           1.08  2.63  1.45   2.53  1.54  1.07   2.60  1.43     2.50
 14           1.18  2.76  1.50   2.68  1.64  1.18   2.82  1.56     2.74
 15           1.16  2.92  1.55   2.71  1.40  0.91   2.31  1.21     2.12
 16           0.63  1.74  0.84   1.47  1.29  0.84   2.13  1.09     1.92
 17           1.37  3.29  1.74   3.11  1.79  1.16   2.95  1.56     2.72
 18           0.89  2.03  1.05   1.95  1.28  0.96   2.24  1.18     2.14
 19           0.89  2.18  1.11   2.00  1.30  0.82   2.12  1.14     1.96

      Team ID

 0   18bb7c10
 1   8602292d
 2   d07537b9
 3   943e8050
 4   cff3d9bb
 5   47c64c55
 6   d3fd31cc
 7   fd962109
 8   5bfb9659
 9   a2d435b3
 10  822bd0ba
 11  b8fd03ef
 12  19538871
 13  b2b47a98
 14  1df6b87e
 15  33c895d4
 16  361ca564
 17  60c6b05f
 18  7c21e445
 19  8cec06e1

 [20 rows x 33 columns],
     Unnamed: 0_level_0   Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk               Player             Nation
 0                    1  Patrick van Aanholt             nl NED
 1                    2        Tammy Abraham            eng ENG
 2                    3            Che Adams            sct SCO
 3                    4     Tosin Adarabioyo            eng ENG
 4                    5               Adrián             es ESP
 ..                 ...                  ...                ...
 527                528          Andi Zeqiri             ch SUI
 528                529  Oleksandr Zinchenko             ua UKR
 529                530         Hakim Ziyech             ma MAR
 530                531           Kurt Zouma             fr FRA
 531                532      Martin Ødegaard             no NOR

     Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0  \
                    Pos              Squad                Age
 0                   DF     Crystal Palace                 29
 1                   FW            Chelsea                 22
 2                   FW        Southampton                 24
 3                   DF             Fulham                 22
 4                   GK          Liverpool                 33
 ..                 ...                ...                ...
 527              FW,DF           Brighton                 21
 528                 DF    Manchester City                 23
 529              MF,FW            Chelsea                 27
 530                 DF            Chelsea                 25
 531                 MF            Arsenal                 21

     Unnamed: 6_level_0 Playing Time               ... Per 90 Minutes         \
                   Born           MP Starts   Min  ...           G-PK G+A-PK
 0                 1990           22     20  1777  ...           0.00   0.05
 1                 1997           22     12  1040  ...           0.52   0.61
 2                 1996           36     30  2667  ...           0.30   0.47
 3                 1997           33     33  2953  ...           0.00   0.00
 4                 1987            3      3   270  ...           0.00   0.00
 ..                 ...          ...    ...   ...  ...            ...    ...
 527               1999            9      0   171  ...           0.00   0.00
 528               1996           20     15  1478  ...           0.00   0.00
 529               1993           23     15  1172  ...           0.15   0.38
 530               1994           24     22  2029  ...           0.22   0.22
 531               1998           14      9   866  ...           0.10   0.31

                                       Unnamed: 36_level_0  \
        xG   xAG xG+xAG  npxG npxG+xAG             Matches
 0    0.07  0.04   0.11  0.07     0.11             Matches
 1    0.51  0.06   0.57  0.51     0.57             Matches
 2    0.33  0.17   0.50  0.33     0.50             Matches
 3    0.03  0.01   0.04  0.03     0.04             Matches
 4    0.00  0.00   0.00  0.00     0.00             Matches
 ..    ...   ...    ...   ...      ...                 ...
 527  0.38  0.04   0.42  0.38     0.42             Matches
 528  0.04  0.06   0.10  0.04     0.10             Matches
 529  0.14  0.28   0.42  0.14     0.42             Matches
 530  0.09  0.00   0.09  0.09     0.09             Matches
 531  0.08  0.21   0.29  0.08     0.29             Matches

                                            Player Link Player ID

 0    https://fbref.com/en/players/5f09991f/Patrick-...  5f09991f
 1    https://fbref.com/en/players/f586779e/Tammy-Ab...  f586779e
 2      https://fbref.com/en/players/f2bf1b0f/Che-Adams  f2bf1b0f
 3    https://fbref.com/en/players/c81d773d/Tosin-Ad...  c81d773d
 4         https://fbref.com/en/players/f76e6b4e/Adrian  f76e6b4e
 ..                                                 ...       ...
 527  https://fbref.com/en/players/d01231f0/Andi-Zeqiri  d01231f0
 528  https://fbref.com/en/players/51cf8561/Oleksand...  51cf8561
 529  https://fbref.com/en/players/6622454d/Hakim-Zi...  6622454d
 530   https://fbref.com/en/players/ce4246f5/Kurt-Zouma  ce4246f5
 531  https://fbref.com/en/players/79300479/Martin-O...  79300479

 [532 rows x 39 columns])

In [6]:
type(season)

tuple

In [7]:
season = season[0]

In [9]:
type(season)

pandas.core.frame.DataFrame

In [ ]:

# Aplanar columnas de múltiples niveles
season.columns = [' '.join(col).strip() for col in season.columns.values]

# Verifica cómo quedaron
print(season.columns.tolist())

['Unnamed: 0_level_0 Squad', 'Unnamed: 1_level_0 # Pl', 'Unnamed: 2_level_0 Age', 'Unnamed: 3_level_0 Poss', 'Playing Time MP', 'Playing Time Starts', 'Playing Time Min', 'Playing Time 90s', 'Performance Gls', 'Performance Ast', 'Performance G+A', 'Performance G-PK', 'Performance PK', 'Performance PKatt', 'Performance CrdY', 'Performance CrdR', 'Expected xG', 'Expected npxG', 'Expected xAG', 'Expected npxG+xAG', 'Progression PrgC', 'Progression PrgP', 'Per 90 Minutes Gls', 'Per 90 Minutes Ast', 'Per 90 Minutes G+A', 'Per 90 Minutes G-PK', 'Per 90 Minutes G+A-PK', 'Per 90 Minutes xG', 'Per 90 Minutes xAG', 'Per 90 Minutes xG+xAG', 'Per 90 Minutes npxG', 'Per 90 Minutes npxG+xAG', 'Team ID']

In [10]:
print(season.head())

  Unnamed: 0_level_0 Squad  Unnamed: 1_level_0 # Pl  Unnamed: 2_level_0 Age  \
0                  Arsenal                       29                    25.9
1              Aston Villa                       24                    25.2
2                 Brighton                       27                    25.8
3                  Burnley                       25                    28.3
4                  Chelsea                       27                    26.0

   Unnamed: 3_level_0 Poss  Playing Time MP  Playing Time Starts  \
0                     53.5               38                  418
1                     48.5               38                  418
2                     51.1               38                  418
3                     42.1               38                  418
4                     60.9               38                  418

   Playing Time Min  Playing Time 90s  Performance Gls  Performance Ast  ...  \
0              3420              38.0               53               38  ...
1              3420              38.0               52               38  ...
2              3420              38.0               39               24  ...
3              3420              38.0               32               20  ...
4              3420              38.0               56               38  ...

   Per 90 Minutes Ast  Per 90 Minutes G+A  Per 90 Minutes G-PK  \
0                1.00                2.39                 1.24
1                1.00                2.37                 1.24
2                0.63                1.66                 0.87
3                0.53                1.37                 0.76
4                1.00                2.47                 1.26

   Per 90 Minutes G+A-PK  Per 90 Minutes xG  Per 90 Minutes xAG  \
0                   2.24               1.36                0.92
1                   2.24               1.38                0.98
2                   1.50               1.34                0.87
3                   1.29               1.03                0.73
4                   2.26               1.64                1.09

   Per 90 Minutes xG+xAG  Per 90 Minutes npxG  Per 90 Minutes npxG+xAG  \
0                   2.29                 1.24                     2.16
1                   2.37                 1.26                     2.25
2                   2.21                 1.15                     2.03
3                   1.76                 0.97                     1.70
4                   2.73                 1.43                     2.53

    Team ID
0  18bb7c10
1  8602292d
2  d07537b9
3  943e8050
4  cff3d9bb

[5 rows x 33 columns]

In [11]:
# Lista de nuevos nombres para las columnas "Unnamed"
new_names = ['Squad', 'Pl', 'Age', 'Poss']  # Continúa la lista según el número de columnas "Unnamed"

# Renombrar las columnas "Unnamed" con los nuevos nombres
season.columns = [
    new_names.pop(0) if col.startswith('Unnamed') else col
    for col in season.columns
]

# Verificar los cambios
print(season.columns.tolist())

['Squad', 'Pl', 'Age', 'Poss', 'Playing Time MP', 'Playing Time Starts', 'Playing Time Min', 'Playing Time 90s', 'Performance Gls', 'Performance Ast', 'Performance G+A', 'Performance G-PK', 'Performance PK', 'Performance PKatt', 'Performance CrdY', 'Performance CrdR', 'Expected xG', 'Expected npxG', 'Expected xAG', 'Expected npxG+xAG', 'Progression PrgC', 'Progression PrgP', 'Per 90 Minutes Gls', 'Per 90 Minutes Ast', 'Per 90 Minutes G+A', 'Per 90 Minutes G-PK', 'Per 90 Minutes G+A-PK', 'Per 90 Minutes xG', 'Per 90 Minutes xAG', 'Per 90 Minutes xG+xAG', 'Per 90 Minutes npxG', 'Per 90 Minutes npxG+xAG', 'Team ID']

In [13]:
season

,Squad,Pl,Age,Poss,Playing Time MP,Playing Time Starts,Playing Time Min,Playing Time 90s,Performance Gls,Performance Ast,...,Per 90 Minutes Ast,Per 90 Minutes G+A,Per 90 Minutes G-PK,Per 90 Minutes G+A-PK,Per 90 Minutes xG,Per 90 Minutes xAG,Per 90 Minutes xG+xAG,Per 90 Minutes npxG,Per 90 Minutes npxG+xAG,Team ID
0,Arsenal,29,25.9,53.5,38,418,3420,38.0,53,38,...,1.00,2.39,1.24,2.24,1.36,0.92,2.29,1.24,2.16,18bb7c10
1,Aston Villa,24,25.2,48.5,38,418,3420,38.0,52,38,...,1.00,2.37,1.24,2.24,1.38,0.98,2.37,1.26,2.25,8602292d
2,Brighton,27,25.8,51.1,38,418,3420,38.0,39,24,...,0.63,1.66,0.87,1.50,1.34,0.87,2.21,1.15,2.03,d07537b9
3,Burnley,25,28.3,42.1,38,418,3420,38.0,32,20,...,0.53,1.37,0.76,1.29,1.03,0.73,1.76,0.97,1.70,943e8050
4,Chelsea,27,26.0,60.9,38,418,3420,38.0,56,38,...,1.00,2.47,1.26,2.26,1.64,1.09,2.73,1.43,2.53,cff3d9bb
5,Crystal Palace,24,29.1,40.6,38,418,3420,38.0,39,29,...,0.76,1.79,0.95,1.71,0.90,0.62,1.52,0.82,1.44,47c64c55
6,Everton,29,26.3,46.4,38,418,3420,38.0,45,32,...,0.84,2.03,1.08,1.92,1.20,0.81,2.01,1.10,1.91,d3fd31cc
7,Fulham,28,25.2,49.7,38,418,3420,38.0,26,18,...,0.47,1.16,0.61,1.08,1.07,0.69,1.76,0.95,1.64,fd962109
8,Leeds United,23,26.1,57.3,38,418,3420,38.0,60,45,...,1.18,2.76,1.47,2.66,1.46,1.10,2.57,1.38,2.48,5bfb9659
9,Leicester City,27,26.5,54.3,38,418,3420,38.0,64,45,...,1.18,2.87,1.42,2.61,1.47,0.89,2.36,1.22,2.11,a2d435b3
10,Liverpool,28,26.8,62.1,38,418,3420,38.0,65,43,...,1.13,2.84,1.55,2.68,1.78,1.27,3.05,1.65,2.92,822bd0ba
11,Manchester City,24,26.1,63.5,38,418,3420,38.0,82,55,...,1.45,3.61,2.03,3.47,1.80,1.19,2.99,1.61,2.81,b8fd03ef
12,Manchester Utd,29,25.6,55.7,38,418,3420,38.0,70,51,...,1.34,3.18,1.58,2.92,1.58,1.10,2.68,1.35,2.45,19538871
13,Newcastle Utd,27,27.1,38.8,38,418,3420,38.0,44,26,...,0.68,1.84,1.00,1.68,1.14,0.76,1.91,1.00,1.76,b2b47a98
14,Sheffield Utd,27,26.7,41.7,38,418,3420,38.0,19,13,...,0.34,0.84,0.42,0.76,0.86,0.66,1.52,0.78,1.43,1df6b87e
15,Southampton,29,26.6,52.0,38,418,3420,38.0,47,33,...,0.87,2.11,1.11,1.97,1.09,0.68,1.77,0.96,1.64,33c895d4
16,Tottenham,24,27.2,51.6,38,418,3420,38.0,66,50,...,1.32,3.05,1.61,2.92,1.40,0.93,2.33,1.29,2.22,361ca564
17,West Brom,30,26.4,37.9,38,418,3420,38.0,33,20,...,0.53,1.39,0.76,1.29,0.94,0.64,1.59,0.86,1.50,60c6b05f
18,West Ham,24,27.8,43.2,38,418,3420,38.0,60,46,...,1.21,2.79,1.53,2.74,1.46,1.04,2.50,1.37,2.41,7c21e445
19,Wolves,27,26.3,49.3,38,418,3420,38.0,34,21,...,0.55,1.45,0.79,1.34,0.96,0.63,1.60,0.88,1.51,8cec06e1

 ## Descripción de las columnas
Squad: El nombre del equipo (por ejemplo, Arsenal, Aston Villa, etc.).

Pl: Número de jugadores disponibles en el equipo.

Age: Edad promedio de los jugadores del equipo.

Poss: Porcentaje promedio de posesión de balón por el equipo durante la temporada.

Playing Time MP: Número total de partidos jugados.

Playing Time Starts: Número de partidos en los que un jugador ha sido titular.

Playing Time Min: Total de minutos jugados en la temporada.

Playing Time 90s: Total de 90 minutos equivalentes jugados (equivalente a las veces que un jugador jugó un partido completo).

Performance Gls: Goles marcados por los jugadores del equipo.

Performance Ast: Asistencias de los jugadores del equipo.

Per 90 Minutes Gls: Promedio de goles por cada 90 minutos jugados.

Per 90 Minutes Ast: Promedio de asistencias por cada 90 minutos jugados.

Per 90 Minutes G+A: Promedio combinado de goles y asistencias por cada 90 minutos.

Per 90 Minutes G-PK: Promedio de goles por cada 90 minutos jugados, excluyendo los goles de penalti.

Per 90 Minutes xG: Promedio de "goles esperados" (xG, una métrica avanzada que calcula la calidad de las oportunidades de gol) por cada 90 minutos jugados.

Per 90 Minutes npxG: Promedio de "goles esperados no relacionados con penalti" por cada 90 minutos jugados.

Team ID: (un código hash o un identificador de base de datos para el equipo).